# Generated by Django 4.2 on 2025-06-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocuments',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
